"""creating database

Revision ID: 1e51b0697604
Revises: 
Create Date: 2024-11-14 13:58:09.250781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e51b0697604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('auth_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('book_id', 'auth_name')
    )
    op.create_table('book_shelf',
    sa.Column('shelf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shelf_id')
    )
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bname', sa.String(length=64), nullable=False),
    sa.Column('pub_year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('shelf_id', sa.Integer(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('locations',
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('loc_name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('pincode')
    )
    op.create_table('readers',
    sa.Column('reader_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('f_name', sa.String(length=64), nullable=False),
    sa.Column('l_name', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('reader_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exchange',
    sa.Column('exch_id', sa.Integer(), nullable=False),
    sa.Column('reader_1', sa.Integer(), nullable=True),
    sa.Column('reader_2', sa.Integer(), nullable=True),
    sa.Column('book_1', sa.Integer(), nullable=True),
    sa.Column('book_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_1'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['book_2'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['reader_1'], ['readers.reader_id'], ),
    sa.ForeignKeyConstraint(['reader_2'], ['readers.reader_id'], ),
    sa.PrimaryKeyConstraint('exch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange')
    op.drop_table('readers')
    op.drop_table('locations')
    op.drop_table('books')
    op.drop_table('book_shelf')
    op.drop_table('authors')
    # ### end Alembic commands ###
